### ISSUE TITLE
Provide CSV table of the catalog

### ISSUE THREAD

**Issue by lupinix** [mattiaverga/OpenNGC#10]
Hi,

can you provide a csv table of the catalog? This is easier to use for most cases, e.g. to read in by other applications. I found something in skychart subfolder but I'm not sure about this.

Greetings,
Christian

**Comment by mattiaverga** [comment]
Done in commit b46012e31242f5844853f0280510f3cfefc3cbfd

**Comment by lupinix** [comment]
Thank you :)
