### ISSUE TITLE
Provide column for common names

### ISSUE THREAD

**Issue by lupinix** [mattiaverga/OpenNGC#11]
Hi,

can you (or I) add a column for common names (like Andromeda Galaxy for NGC224)? I know that we already have that information in the table together with other catalog identifiers, that is not so easy to use as a program would require some way to find out what the common name(s) is.

I already extracted that information from SIMBAD and would add a column for that in the table. What do you think about that?

Greetings,
Christian

**Comment by mattiaverga** [comment]
Yes, it wasn't easy and I already planned to add the new column.
Commit 4964171c1f1326218c88d2a88b802a34480b6e10 transfers common names from "Names" column (which become "Identifiers") to the newly created "Common names" column.
Be advised that some object have more than one name, I've added them separated by commas.

**Comment by lupinix** [comment]
Wow that was fast! Thank you very much!
