### ISSUE TITLE
Magnitude missing for some Messier objects

### ISSUE THREAD

**Issue by kbahey** [mattiaverga/OpenNGC#15]
Hello, 

Thank you for a great project.

Some objects in the Messier catalog do not have a V-Mag value.

They are:

Name   Messier
IC4715 024 
NGC0650 076 
NGC1952 001 
NGC1976 042 
NGC1982 043 
NGC2068 078 
NGC3556 108 
NGC3587 097 
NGC3623 065 
NGC3992 109 
NGC4382 085 
NGC4621 059 
NGC4649 060 
NGC6093 080 
NGC6121 004 
NGC6514 020 
NGC6523 008 
NGC6531 021 
NGC6618 017 
NGC6626 028 
NGC6715 054 
NGC6720 057 
NGC6779 056 
NGC6853 027 
NGC6994 073 
NGC7078 015 
NGC7654 052

**Comment by mattiaverga** [comment]
Thanks, I will try to find valid data sources for those values. I don't want to just use Wikipedia or other 'unverified' sources like that.

**Comment by kbahey** [comment]
Thank you so much. This is very helpful.
