### ISSUE TITLE
Messier M40 (Winnecke 4) and M45 (Pleiades) missing

### ISSUE THREAD

**Issue by kbahey** [mattiaverga/OpenNGC#16]
The Messier objects M40 (Winnecke 4), and M45 (Pleiades) are missing from the Open NGC database.

**Comment by lupinix** [comment]
Are they really missing in context of an NGC/IC database? Both Messier objects don't have NGC or IC identifiers.

**Comment by mattiaverga** [comment]
See https://github.com/mattiaverga/OpenNGC/blob/master/README.md#the-addendum

> Note that two Messier objects (M40 and M45) haven't got any NGC or IC designation, so they're listed only in the addendum.

**Comment by kbahey** [comment]
Thank you. That completes the Messier catalog.
