### ISSUE TITLE
NGC 1649

### ISSUE THREAD

**Issue by ultrapre** [mattiaverga/OpenNGC#20]
In 1888 version NGC 1649 seems to be OCL but not GCL. Some unreliable source indicate it as G.

**Comment by mattiaverga** [comment]
Yeah, this is one of those objects with an extremely uncertain identification:
- NED considers NGC1649 and NGC1652 the same object with a generic `*Cl` type
- SIMBAD considers NGC1649 a totally different object situated at other coordinates; the object at the same NED coords is NGC1652, which is considered Globular Cluster
- LEDA considers NGC1649 and NGC1652 the same object like NED, but at totally different coords

However, while merging data from different sources I've put wrong data in OpenNGC. I'm going to consider NGC1649 and NGC1652 the same object at coordinates provided by NED, but maintaining the `GCl` type and correcting diamaters and other data from SIMBAD's NGC1652 entry.

Thanks for the report.
