### ISSUE TITLE
More fix offer

### ISSUE THREAD

**Issue by ultrapre** [mattiaverga/OpenNGC#21]
I make a new fix file and notes in https://github.com/ultrapre/DSO/tree/master/%E5%85%B6%E4%BB%96/type_fix_for_ngcic

maybe it can help you :)

welcome for any question

**Comment by mattiaverga** [comment]
Thanks, I'll look into it.

**Comment by mattiaverga** [comment]
So, the source for type column in ONGC is NED by first instance, then SIMBAD. In some cases where the type wasn't clear enough I chose between the two (or three, considering LEDA).
If there is some specific doubt about one object I will be glad to reconsider the type choice, but I'm not going to try to consider all the NGC/IC catalogs out there...

Closing this, for the moment.
