### ISSUE TITLE
Add some common names

### ISSUE THREAD

**Issue by rumengb** [mattiaverga/OpenNGC#25]
"NGC1952" => "Crab nebula",
"NGC2573" => "Polarissima Australis",
"NGC3172" => "Polarissima Borealis",
"NGC3918" => "Blue planetary nebula",
"NGC4435" => "The Eyes",
"NGC4438" => "The Eyes",
"NGC4567" => "Siamese Twins",
"NGC6523" => "Hourglass nebula",
"NGC6960" => "Filamentary nebula",
"NGC6992" => "Network nebula",
"NGC6995" => "Network nebula"

**Comment by mattiaverga** [comment]
Thanks
