### ISSUE TITLE
Open NGC has some incorrect reference on duplicate records

### ISSUE THREAD

**Issue by js-dieu** [mattiaverga/OpenNGC#27]
Hello

Thanks for providing this project! It is quite helpful. :)

I think there are 2 errors in duplicate's original reference:
 - IC4222 incorrectly maps NGC0879 instead of IC0879
 - IC5327 incorrectly maps NGC1495 instead of IC1495

I made PR  #26 to fix that.

Thanks!

**Comment by mattiaverga** [comment]
Yup, thank you! Those were definitely my errors.
