### ISSUE TITLE
V-Mag missing for many object, is B-Mag good to use

### ISSUE THREAD

**Issue by artyom-beilis** [mattiaverga/OpenNGC#29]
I'm developer of https://github.com/artyom-beilis/skyhopper/ web application that helps navigating the night sky using cell-phone gyros and gravity senors.

I use OpenNGC as core catalogue for DSO objects. I used V-Mag for filtering DSO objects that are too dim. However I had found I filtered many objects that had no V-Mag but only B-Mag.

I'm not that experienced with this classification. Should I use B-Mag instead of minimum of B-Mag/V-Mag for filtering.

Using min(B-Mag,V-Mag) significantly increases the number of objects I need to display and I wonder:

1. Why there many objects with V-Mag missing but B-Mag present
2. What is recommended way to filter objects by visual brightness

**Comment by mattiaverga** [comment]
Objects magnitudes in OpenNGC are mostly taken from Simbad, which seems to provide V-Mag very rarely. HyperLEDA provides only B-Mag magnitudes for galaxies and I used that for many galaxies for which data was not available in Simbad.
For several other objects I tried to integrate missing magnitudes from other catalogs (HEASARC's catalogs mainly). But, yes, there are too few objects with V band magnitudes in the catalog. I will look in finding a solution.

Meanwhile, I think you can try an approach like "V-Mag or B-Mag if V is not available". B-Mag is the magnitude in blue, which is often referred as photographic magnitude, and I think it's the best substitute to V-Mag.

**Comment by artyom-beilis** [comment]
Thank You Very Much.

You did great project!
