### ISSUE TITLE
Galaxy size

### ISSUE THREAD

**Issue by pchev** [mattiaverga/OpenNGC#5]
I generally like the size of the galaxy in the catalog, it much better match the visual aspect than the magnitude 25 isophot in Leda. 
But in some case it is too small. 
For example M31 is given a major axis of 44' (no typo, checked in Simbad) but on any short exposure image you get about 150'.
NGC7331, morphologically the same as M31, present the same problem.

**Comment by mattiaverga** [comment]
Yes, I saw that there are some sizes that are quite strange... those measures in SIMBAD are mainly taken from 2MASS in infrared, maybe it's the cause of the big difference with the magnitude 25 isophot in Leda.
I think in these cases where there is a clear difference I can revert to Leda values (and add a note about that to the object).

I'm now splitting all galaxy groups in separate members, when I'm done with that I will take a look to these diameters. In the meantime, I can use this issue as a tracker for objects that need to be tweaked, if you see any other please add a comment down here.

Thanks

**Comment by mattiaverga** [comment]
While splitting galaxy groups in single members I realized that diameters data imported from Simbad gives really weird values also for small galaxies...
I decided to revert back to Leda diameters and position angles, I'm now checking galaxies which don't have a PGC name associated, after that I will make a script to download and import data. Where Leda don't provide diameters data I will try to maintain Simbad data (if available) and add a note to the entry.

**Comment by mattiaverga** [comment]
In commit 953d9db47e76028b651664c07975114df0472e73 I reverted galaxies data to LEDA values (and I've checked correspondence between NED and LEDA).
Only 43 galaxies have retained Simbad data because LEDA doesn't give diameters.
