### ISSUE TITLE
Planetary Nebulae magnitudes

### ISSUE THREAD

**Issue by mattiaverga** [mattiaverga/OpenNGC#6]
Planetary Nebulae magnitudes available from SIMBAD are crazy: M57 mag. 15; M27 mag 13.75... maybe are referred to the central star?

I need to find a better source for that (plnebulae table from HEASARC does not provide B-mag / V-mag).

**Comment by pchev** [comment]
I have the gpn.txt text file I use to make the CdC GPN catalog here https://sourceforge.net/p/skychart/code/HEAD/tree/trunk/tools/cat/gpn/src/
This file is build from catalog V/84 by merging the various tables, and add V magnitude from the pln.fits file.

In gpn.txt you can find NGC/IC name in column 31 and Vmag in column 77.

I also add an Hbeta magnitude derived from the Hbeta flux. It is in column 85 and can be used for Bmag (maybe add a note for that)

**Comment by mattiaverga** [comment]
Imported B-Mag from LEDA
