### ISSUE TITLE
Bright nebula missing magnitude and size

### ISSUE THREAD

**Issue by pchev** [mattiaverga/OpenNGC#8]
Many bright nebula have no magnitude or no size.

As a result the brightest part of the Veil nebula  NGC6992 is not show on the CdC chart because it as no magnitude and no size, so considered as a small faint object.

Hyperleda as a convenient size and Bmag  for most of this objects and can be used to fill the missing data.
for example:
pleinpot/bin/exe/psql -c "select pgc, objname, al2000, de2000, bt as Bmag, bvt as Vmag, brief as sbr, objtype, type, round(cast((10 ^ logd25)/10 as numeric),2) as Smax,round(cast((10 ^ logd25)/10 / (10 ^ logr25) as numeric),2) as Smin , pa, hl_names(pgc) from meandata where objname='NGC6992'" hl

   pgc   | objname |   al2000   |   de2000   | bmag | vmag | sbr | objtype | type | smax  | smin | pa | hl_names 
---------+---------+------------+------------+------+------+-----+---------+------+-------+------+----+----------
 3517687 | NGC6992 | 20.9384706 | 31.7380539 |    7 |      |     | ?       |      | 59.98 | 8.00 |    | NGC6992
(1 row)

**Comment by mattiaverga** [comment]
Thanks, I considered LEDA data only from galaxies, but it can indeed be useful also for nebulae.
I've imported B-mag and sizes from LEDA for nebulae which had no data. I also used LEDA B-mag as default for Planetary Nebulae because is much more complete than the data available in Revised NGC.
